# Generated by Django 5.0.3 on 2024-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image',
            new_name='image2',
        ),
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.ImageField(default=None, upload_to='property_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image6',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image7',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
    ]
